Repository KungFuFurby/AddMusicKFF, pull requests merged in 2021-04, with the labels that each got.

#86 Implement pitch slide delays in SFX
  asm/main.asm
  readme_files/sound_effects.html
Labels: documentation, spc-side

#83 Terminate SFX sequence and don't disable SFX flag when CPUIO1 SFX triggers
  asm/main.asm
Labels: spc-side

#98 Add rest VCMD for SFX
  1DF9/06 Yoshi gulp.txt
  1DF9/1A Grinder click 1.txt
  1DF9/1D Time running low 1.txt
  1DF9/1F Koopaling defeated.txt
  1DF9/27 Firework bang 1.txt
  1DF9/29 Firework bang 2.txt
  1DFC/09 Bullet bill.txt
  1DFC/0A Egg hatch.txt
  1DFC/0B Item into reserve.txt
  1DFC/0F Door.txt
  1DFC/1D Time low 2.txt
  1DFC/1F Yoshi.txt
  1DFC/20 Koopaling land in lava.txt
  1DFC/24 P-switch time low.txt
  1DFC/26 Swooper.txt
  asm/main.asm
Labels: spc-side

#82 Don't reset noise clock while SFX is utilizing it when changing songs
  asm/Commands.asm
  asm/main.asm
Labels: spc-side

#48 Don't use fine tune with sound effect notes
  asm/main.asm
Labels: spc-side

#101 Rare P-Switch/Starman bug fix
  asm/SNES/patch.asm
Labels: bug, snes-side
